name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/split_cat_morphometry:latest --tag islasgeci/split_cat_morphometry:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/split_cat_morphometry:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run --volume $PWD:/workdir islasgeci/split_cat_morphometry:latest make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        verbose: true
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/split_cat_morphometry:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/split_cat_morphometry:${GITHUB_SHA:0:4}
